#!/usr/bin/env python3
"""Synthesise placeholder morph audio so the site is testable before real
renders exist.

Writes an 11-step "whoosh" morph for every (method, example) directory named in
data/examples.json. The placeholder morph brightens, tightens its envelope and
rises in pitch as alpha goes 0 -> 1, so the sliders, waveform strip and envelope
overlay all show something meaningful.

    python3 tools/make_placeholders.py            # fill only empty dirs
    python3 tools/make_placeholders.py --force    # overwrite

Delete the generated files (or just overwrite the directory) once real audio is
rendered:

    python3 tools/make_placeholders.py --clean
"""

import argparse
import json
import math
import os
import random
import struct
import wave

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(HERE, "data", "examples.json")
MARKER = ".placeholder"

SR = 22050
DUR = 3.0
STEPS_DEFAULT = 11


def synth(alpha, seed):
    """One morph step. alpha=0 is slow/dark/quiet, alpha=1 fast/bright/loud."""
    rng = random.Random(seed)
    n = int(SR * DUR)

    # envelope: wide gentle swell -> tight fast transient
    width = 0.55 - 0.40 * alpha          # relative width of the swell
    centre = 0.52 - 0.12 * alpha
    gain = 0.30 + 0.45 * alpha

    # brightness: one-pole lowpass, higher alpha = less smoothing
    a_lp = 0.75 - 0.60 * alpha

    # tonal component rides an octave up across the morph
    f0 = 180.0 * (2.0 ** (1.5 * alpha))

    out = [0.0] * n
    lp = 0.0
    ph = 0.0
    dph = 2.0 * math.pi * f0 / SR
    for i in range(n):
        t = i / n
        e = math.exp(-((t - centre) ** 2) / (2.0 * width * width * 0.25))
        noise = rng.uniform(-1.0, 1.0)
        lp = a_lp * lp + (1.0 - a_lp) * noise
        tone = math.sin(ph) * (0.18 + 0.22 * alpha)
        ph += dph * (1.0 + 0.35 * t * alpha)     # slight upward glide
        out[i] = gain * e * (lp * 1.6 + tone)

    peak = max(1e-6, max(abs(v) for v in out))
    scale = 0.9 / peak * (0.55 + 0.45 * alpha)   # keep loudness trend visible
    return [max(-1.0, min(1.0, v * scale)) for v in out]


def write_wav(path, samples):
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(b"".join(
            struct.pack("<h", int(v * 32767)) for v in samples))


def dirs_from_manifest():
    with open(MANIFEST) as f:
        man = json.load(f)
    steps = man.get("steps", STEPS_DEFAULT)
    pattern = man.get("pattern", "step_{i}.wav")
    out = []
    for ex in man["examples"]:
        for key, m in ex["methods"].items():
            out.append((m["dir"], m.get("steps", ex.get("steps", steps)),
                        m.get("pattern", pattern), ex["id"] + "/" + key))
    # de-duplicate shared dirs
    seen, uniq = set(), []
    for d in out:
        if d[0] in seen:
            continue
        seen.add(d[0])
        uniq.append(d)
    return uniq


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="overwrite existing files")
    ap.add_argument("--clean", action="store_true", help="delete generated placeholders")
    args = ap.parse_args()

    for rel, steps, pattern, tag in dirs_from_manifest():
        d = os.path.join(HERE, rel)
        marker = os.path.join(d, MARKER)

        if args.clean:
            if os.path.exists(marker):
                for f in os.listdir(d):
                    os.remove(os.path.join(d, f))
                print("cleaned", rel)
            continue

        os.makedirs(d, exist_ok=True)
        existing = [f for f in os.listdir(d) if f.endswith(".wav")]
        if existing and not args.force and not os.path.exists(marker):
            print("skip (real audio present)", rel)
            continue
        if existing and not args.force and os.path.exists(marker):
            print("skip (already generated)", rel)
            continue

        seed = abs(hash(tag)) % (2 ** 31)
        for i in range(steps):
            alpha = i / (steps - 1) if steps > 1 else 0.0
            name = pattern.replace("{i}", "%02d" % i).replace("{n}", str(i))
            write_wav(os.path.join(d, name), synth(alpha, seed))
        open(marker, "w").write("generated by tools/make_placeholders.py\n")
        print("wrote %d steps ->" % steps, rel)


if __name__ == "__main__":
    main()
